language: nix
nix: 2.0.4
env:
  - NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/19.03.tar.gz"
before_install:
  nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs_1903
  nix-channel --update nixpkgs_1903
  nix-shell travis-shell.nix --run ./scripts/bump-fixed-build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: v2.1
